export default Object.freeze([
    { key: 'trucknumber', label: '车牌号' },
    { key: 'distance', label: '里程(km)' },
    { key: 'speed', label: '车速(km/h)' },
    { key: 'fuelvol', label: '油量(L)' },
    { key: 'lefttirepressure', label: '左轮胎压(kpa)' },
    { key: 'lefttiretemp', label: '左轮胎温' },
    { key: 'righttirepressure', label: '右轮胎压(kpa)' },
    { key: 'righttiretemp', label: '右轮胎温' },
    { key: 'gpsx', label: '位置经度' },
    { key: 'gpsy', label: '位置纬度' },
    { key: 'time', label: '时间', type: 'date' },
    { key: 'lock1', label: '安全锁1' },
    { key: 'lock2', label: '安全锁2' },
    { key: 'lock3', label: '安全锁3' },
    { key: 'lock4', label: '安全锁4' },
    { key: 'lock5', label: '安全锁5' },
])